edition="2021"
max_width = 120
reorder_imports = true
brace_style = "SameLineWhere"
blank_lines_upper_bound = 1
imports_granularity = "crate"
group_imports = "StdExternalCrate"
format_code_in_doc_comments = true
